// DO NOT MANUALLY EDIT - THIS FILE IS AUTOMATICALLY GENERATED

export type IntrospectedMeasure = string;
export type IntrospectedDimension = string;
export type IntrospectedTimeDimension = string;
export type IntrospectedSegment = string;
